import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./_components/sidebar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <div
       className={cn("flex min-h-screen w-full",inter.className)}>
        <Sidebar />
        {children}
      </div>
  );
}
