import { cn } from "@/lib/utils";
import { Sidebar } from "./_components/sidebar";
import { Breadcrumb } from "./_components/breadcrumb";
// import { SearchCommand } from "./_components/search-command";
import { Actions } from "./_components/actions";
import AuthProvider from "@/context/Auth";


// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };
//
export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const user = {
        fullName: "Yosef Mahmoud",
        profilePicture: ""
    }
    return (
        <div
            className={"flex w-full h-screen p-6 space-x-4 bg-dark-tremor-background-muted"}>
          <AuthProvider>
            <Sidebar />
            <div className="flex flex-col items-center justify-center w-full h-full space-y-4">
                <div className="w-full rounded-lg border bg-card text-card-foreground shadow-sm py-3 px-4">
                    <header className="w-full h-full flex items-center justify-between gap-x-20">
                        <Breadcrumb />
                        {/* <SearchCommand /> */}
                        <Actions user={user} />
                    </header>
                </div>
                    <div className="w-full h-full bg-dark-tremor-brand-faint">{children}</div>
            </div>
            </AuthProvider>

        </div>
    );
}
