import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "./providers";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import { Rubik } from "next/font/google";


const rubik = Rubik({ subsets: ["arabic", "latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={cn("light",rubik.className)}>
                <Providers>
                        {children}
                </Providers>
                <Toaster />
            </body>
        </html>
    );
}
